"""alter distance name to value.

Revision ID: 4aef2c068003
Revises: 8f3763d6dd55
Create Date: 2024-12-25 15:24:23.095508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4aef2c068003'
down_revision: Union[str, None] = '8f3763d6dd55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control', sa.Column('value', sa.Integer(), nullable=True))
    op.drop_column('control', 'distance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control', sa.Column('distance', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('control', 'value')
    # ### end Alembic commands ###
