"""adding user col for custom control.

Revision ID: 7b78e1c1fad7
Revises: bdd8b0806712
Create Date: 2024-12-25 00:35:06.854438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7b78e1c1fad7'
down_revision: Union[str, None] = 'bdd8b0806712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customcontrol', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'customcontrol', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customcontrol', type_='foreignkey')
    op.drop_column('customcontrol', 'user_id')
    # ### end Alembic commands ###
