"""making distance field to be nullable.

Revision ID: 8f3763d6dd55
Revises: ab997b29f946
Create Date: 2024-12-25 14:38:47.282542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8f3763d6dd55'
down_revision: Union[str, None] = 'ab997b29f946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control', sa.Column('distance', sa.Integer(), nullable=True))
    op.add_column('customcontrol', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True))
    op.drop_column('customcontrol', 'distance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customcontrol', sa.Column('distance', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('customcontrol', 'description')
    op.drop_column('control', 'distance')
    # ### end Alembic commands ###
