"""making distance field to be nullable.

Revision ID: ab997b29f946
Revises: 2399f6709889
Create Date: 2024-12-25 14:13:40.517391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ab997b29f946'
down_revision: Union[str, None] = '2399f6709889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('control', 'distance')
    op.add_column('customcontrol', sa.Column('distance', sa.Integer(), nullable=True))
    op.drop_column('customcontrol', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customcontrol', sa.Column('description', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.drop_column('customcontrol', 'distance')
    op.add_column('control', sa.Column('distance', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
