"""cascade on controls.

Revision ID: ad38f3fbb25f
Revises: a1f12c69d7ae
Create Date: 2024-12-30 03:14:42.406031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ad38f3fbb25f'
down_revision: Union[str, None] = 'a1f12c69d7ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('control_custom_control_id_fkey', 'control', type_='foreignkey')
    op.create_foreign_key(None, 'control', 'customcontrol', ['custom_control_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'control', type_='foreignkey')
    op.create_foreign_key('control_custom_control_id_fkey', 'control', 'customcontrol', ['custom_control_id'], ['id'])
    # ### end Alembic commands ###
