"""added BasicControl Model.

Revision ID: dc0693c2f723
Revises: d7d6c368cf75
Create Date: 2024-11-28 19:05:02.649974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dc0693c2f723'
down_revision: Union[str, None] = 'd7d6c368cf75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basiccontrol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # insert data into the table
    from sqlalchemy.sql import text
    conn = op.get_bind()
    conn.execute(text("INSERT INTO basiccontrol (name) VALUES ('Go Forward')"))
    conn.execute(text("INSERT INTO basiccontrol (name) VALUES ('Go Backward')"))
    conn.execute(text("INSERT INTO basiccontrol (name) VALUES ('Go Left')"))
    conn.execute(text("INSERT INTO basiccontrol (name) VALUES ('Go Right')"))
    conn.execute(text("INSERT INTO basiccontrol (name) VALUES ('Stop')"))
    conn.execute(text("INSERT INTO basiccontrol (name) VALUES ('Change Speed')"))
    
    
    op.add_column('user', sa.Column('car_speed', sa.Integer(), nullable=True, default=50))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'car_speed')
    op.drop_table('basiccontrol')
    # ### end Alembic commands ###
